[package]
name = "obtuiner"
version = "0.1.1"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
installer = { path = "../installer" }
launcher = { path = "../launcher" }
updater = { path = "../updater" }
core_domain = { path = "../core_domain" }
plugin_api = { path = "../plugin_api" }
